name: CD Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - "completed"

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Pull Docker-Image from DockerHub
      run: sudo docker pull nitin03/python-app:latest
    - name: Delete the old Docker Container
      run: sudo docker rm -f pearlthoughts || true
    - name: Run Docker Container
      run: sudo docker run -d -p 5000:5000 --name pearlthoughts nitin03/python-app
